export const keyWords = [
  "Algorithms",
  "Accounting Software",
  "Active Listening",
  "Analytical Skills",
  "Android Developer",
  "Applications",
  "Artificial Intelligence (AI)",
  "AutoCAD",
  "Automated Marketing Software",
  "Automation",
  "Azure",
  "Benchmarking",
  "Big Data",
  "Blogging",
  "Blueprint Design",
  "Budget Planning",
  "C++",
  "Calculating",
  "Certifications",
  "Client Relations",
  "Cloud Computing",
  "Cloud/SaaS Services",
  "Coding",
  "Communicating Complex Information in Digestible Amounts",
  "Compiling Statistics",
  "Compliance",
  "Computer Programming",
  "Configuration",
  "Configure Database Software",
  "Content Management",
  "Content Management Systems (CMS)",
  "Continually Review Processes for Improvement ",
  "Creativity",
  "Customer Relationship Management (CRM)",
  "Customer Support",
  "Cyber Security",
  "Data Analytics",
  "Data Mining",
  "Data Scientist",
  "Database Design",
  "Database Management",
  "Database Software",
  "Debugging",
  "Design",
  "Development",
  "Digital Communications",
  "Digital Marketing",
  "Digital Media",
  "Digital Photography",
  "Documentation",
  "Email",
  "Engineering",
  "Enterprise Resource Planning (ERP) Software",
  "Ethical Hacking",
  "Fabrication",
  "Flexibility",
  "Following Specifications",
  "Front End Web Developer",
  "Graphic Design",
  "Hardware",
  "Hardware Description Language (HDL)",
  "Hardware Verification Tools and Techniques",
  "HTML",
  "Human Resources Software",
  "ICT (Information and Communications Technology)",
  "Implementation",
  "Information Management",
  "Information Security",
  "Information Security Analyst",
  "Information Technology",
  "Infrastructure",
  "Inventory Management",
  "iOS Developer",
  "IP Setup",
  "IT Manager",
  "JavaScript",
  "js",
  "Languages",
  "Leadership",
  "Maintenance",
  "Malware Prevention and Detection",
  "Manage Remote Working Teams",
  "Manufacturing",
  "Market Research Analyst",
  "Mechanical Maintenance",
  "Medical Billing",
  "Medical Coding",
  "Mentoring",
  "Microsoft Office Certifications",
  "Mobile Applications",
  "Modeling",
  "Modification",
  "Needs Analysis",
  "Network Architecture",
  "Network Security",
  "Networking",
  "New Technologies",
  "NoSQL",
  "Numeracy",
  "Open Source Technology Integration",
  "Operating Systems",
  "Operations",
  "Optimizing Website Performance",
  "Performance Review",
  "PHP",
  "Problem Solving",
  "Product Manager",
  "Productivity Software",
  "Programming",
  "Project Manager",
  "Project Planning",
  "Python",
  "Quality Assurance",
  "Quality Control",
  "Quantitative Reports",
  "Quantitative Research",
  "Query Software",
  "Requirements Gathering",
  "Research",
  "Restoration",
  "Ruby",
  "SaaS",
  "Scheduling",
  "Scrum Master",
  "Search Engine Optimization (SEO)",
  "Security",
  "Servers",
  "Social Media Platforms",
  "Software",
  "Software Developer",
  "Software Engineer",
  "Software Quality Assurance (QA) Engineer",
  "Solution Delivery",
  "Sonography",
  "SQL",
  "Statistical Analysis",
  "Storage",
  "Structural Analysis",
  "Structures",
  "Subject Matter Experts (SMEs)",
  "System Reboot",
  "Systems Analysis",
  "Tables and Queries",
  "Task Delegation",
  "Task Management",
  "Teamwork",
  "Tech Support",
  "Technical Documentation",
  "Technical Support",
  "Technical Support Engineer",
  "Technology",
  "Telecommunications",
  "Testing",
  "Tools",
  "Training",
  "Troubleshooting",
  "Usability",
  "UX Design",
  "Video Creation",
  "Web Analytics",
  "Wireless Modems/Routers",
  "WordPress",
  "WordPress Plugin Design	"
];

export const roles = [
  "Frontend Developer",
  "Backend Developer",
  "Fullstack Developer",
  "Mobile Developer",
  "UI/UX Designer",
  "Project Manager",
  "Data Analyst",
  "Quality Assurance",
  "Software Tester",
  "Other"
];
